#!/usr/bin/env python3
"""
Test script generated by browse-to-test.

This script uses shared utilities from the test_setup package.
"""

import asyncio
from playwright.async_api import async_playwright

import test_setup_java.test_utilities.py.*;
import test_setup_java.framework_helpers.py.*;

# Generated test script using browse-to-test
# Framework: playwright
# Language: java
# This script was automatically generated from browser automation data
import com.microsoft.playwright.*;
import java.util.concurrent.CompletableFuture;

public class PlaywrightTest {

    public static void main(String[] args) {
        CompletableFuture.runAsync(() -> {
            try (Playwright playwright = Playwright.create()) {
                Browser browser = playwright.chromium().launch();
                Page page = browser.newPage();

                page.close();
                browser.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        });
    }
}