#!/usr/bin/env python3
"""
Test script generated by browse-to-test.

This script uses shared utilities from the test_setup package.
"""

import asyncio
from playwright.async_api import async_playwright

import { TestActionError, replace_sensitive_data, safe_action, try_locate_and_act } from './test_utilities.py';
import { safe_action, try_locate_and_act } from './framework_helpers.py';

# Generated test script using browse-to-test
# Framework: playwright
# Language: javascript
# This script was automatically generated from browser automation data
const { test, expect } = require('@playwright/test');

test('login test', async ({ page }) => {
});