#!/usr/bin/env python3
"""
Test script generated by browse-to-test.

This script uses shared utilities from the test_setup package.
"""

import asyncio
from playwright.async_api import async_playwright

using test_setup_csharp.test_utilities.py;
using test_setup_csharp.framework_helpers.py;

# Generated test script using browse-to-test
# Framework: playwright
# Language: csharp
# This script was automatically generated from browser automation data
using Microsoft.Playwright;
using System.Threading.Tasks;
using System;

namespace PlaywrightTests
{

    public class LoginTest
    {
        public static async Task Main(string[] args)
        {
            using var playwright = await Playwright.CreateAsync();
            await using var browser = await playwright.Chromium.LaunchAsync();
            var page = await browser.NewPageAsync();

            await page.CloseAsync();
            await browser.CloseAsync();
        }
    }
}