/// <summary>
/// Test constants and configuration generated by browse-to-test.
/// </summary>

using System.Collections.Generic;

namespace TestUtilities
{
    public static class TestConstants
    {
        // Default timeouts
        public const int DEFAULT_TIMEOUT = 30000;
        public const int ELEMENT_TIMEOUT = 10000;
        public const int PAGE_LOAD_TIMEOUT = 30000;

        // Default browser options
        public static readonly Dictionary<string, object> DEFAULT_BROWSER_OPTIONS = new()
        {
            { "headless", false },
            { "timeout", DEFAULT_TIMEOUT }
        };

        // Sensitive data placeholder
        public static readonly Dictionary<string, object> SENSITIVE_DATA = new();
    }
}