#!/usr/bin/env python3
"""
Test constants and configuration generated by browse-to-test.
"""

# Default timeouts
DEFAULT_TIMEOUT = 30000
ELEMENT_TIMEOUT = 10000
PAGE_LOAD_TIMEOUT = 30000

# Default browser options
DEFAULT_BROWSER_OPTIONS = {
    'headless': False,
    'timeout': DEFAULT_TIMEOUT,
}

# Sensitive data placeholder
SENSITIVE_DATA = {}