/**
 * Test constants and configuration generated by browse-to-test.
 */

// Default timeouts
export const DEFAULT_TIMEOUT = 30000;
export const ELEMENT_TIMEOUT = 10000;
export const PAGE_LOAD_TIMEOUT = 30000;

// Default browser options
export const DEFAULT_BROWSER_OPTIONS = {
    headless: false,
    timeout: DEFAULT_TIMEOUT,
};

// Sensitive data placeholder
export const SENSITIVE_DATA: Record<string, any> = {};