/**
 * Test constants and configuration generated by browse-to-test.
 */

import java.util.HashMap;
import java.util.Map;

public class TestConstants {
    // Default timeouts
    public static final int DEFAULT_TIMEOUT = 30000;
    public static final int ELEMENT_TIMEOUT = 10000;
    public static final int PAGE_LOAD_TIMEOUT = 30000;

    // Default browser options
    public static final Map<String, Object> DEFAULT_BROWSER_OPTIONS = new HashMap<String, Object>() {{
        put("headless", false);
        put("timeout", DEFAULT_TIMEOUT);
    }};

    // Sensitive data placeholder
    public static final Map<String, Object> SENSITIVE_DATA = new HashMap<>();
}