/**
 * Framework-specific test helpers generated by browse-to-test.
 */

// Playwright Helpers

const { Page } = require('@playwright/test')

// Safe action execution with error handling for Playwright
export async function safeAction(page, actionFunc, stepInfo = '') {
    try {
        return await actionFunc();
    } catch (error) {
        const errorMessage = error instanceof Error ? error.message : String(error);
        if (stepInfo) {
            console.error(`Action failed (${stepInfo}): ${errorMessage}`);
        } else {
            console.error(`Action failed: ${errorMessage}`);
        }
        throw new TestActionError(`Action failed: ${errorMessage}`);
    }
}


// Robust element location and interaction for Playwright
// try_locate_and_act not implemented for javascript + playwright

