/**
 * Shared test utilities generated by browse-to-test.
 */

import java.util.*;
import java.util.concurrent.*;

public class TestUtilities {

// Custom exception classes

// Custom exception for test action failures
public class TestActionError extends Exception {
    public TestActionError(String message) {
        super(message);
    }
}


// Framework-specific utilities

// Safe action execution with error handling for Playwright
// safe_action not implemented for java + playwright


// Robust element location and interaction for Playwright
// try_locate_and_act not implemented for java + playwright


// Helper functions for test actions

// Replace sensitive data placeholders in strings
public static String replaceSensitiveData(String text, Map<String, Object> sensitiveMap) {
    if (text == null || text.isEmpty()) {
        return text;
    }
    
    for (Map.Entry<String, Object> entry : sensitiveMap.entrySet()) {
        String replacementValue = entry.getValue() != null ? entry.getValue().toString() : "";
        text = text.replace("<secret>" + entry.getKey() + "</secret>", replacementValue);
    }
    
    return text;
}


}